# Generated by Django 4.2 on 2024-01-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0008_category_client_pill_product_selloperation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid',
            name='pill',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='client',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='selloperation',
            name='pill',
        ),
        migrations.RemoveField(
            model_name='selloperation',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Paid',
        ),
        migrations.DeleteModel(
            name='Pill',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SellOperation',
        ),
    ]
