# Generated by Django 4.2 on 2024-01-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maindata', '0009_remove_paid_pill_remove_pill_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name=' الاسم')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='  الفون')),
                ('national_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='  رقم البطاقة ')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='   العنوان ')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الاضافة')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='  ملاحظات ')),
                ('file', models.FileField(blank=True, null=True, upload_to='client_files/', verbose_name='  ملف')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maindata.user')),
            ],
            options={
                'verbose_name': '   عميل',
                'verbose_name_plural': '  العملاء ',
            },
            bases=('maindata.user',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maindata.user')),
            ],
            options={
                'verbose_name': '   عامل',
                'verbose_name_plural': '  عمال ',
            },
            bases=('maindata.user',),
        ),
    ]
