# Generated by Django 4.2 on 2024-01-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(blank=True, max_length=200, null=True, verbose_name=' وصف')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='  الوزن')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='  السعر')),
                ('pill', models.FileField(blank=True, null=True, upload_to='package_pill_files/', verbose_name='  صورة من الفاتورة')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='  ملاحظات ')),
            ],
            options={
                'verbose_name': '   عامل',
                'verbose_name_plural': '  عمال ',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='  رقم البطاقة '),
        ),
    ]
