# Generated by Django 4.2 on 2024-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0011_package_alter_user_national_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': '   طلب', 'verbose_name_plural': '  الطلبات '},
        ),
        migrations.AddField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, verbose_name='كود الطلب'),
        ),
        migrations.AddField(
            model_name='package',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الطلب'),
        ),
    ]
