# Generated by Django 4.2 on 2024-01-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0012_alter_package_options_package_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=14, null=True, verbose_name='كود الطلب'),
        ),
        migrations.CreateModel(
            name='ChargeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(blank=True, max_length=200, null=True, verbose_name=' من عنوان')),
                ('to_place', models.CharField(blank=True, max_length=200, null=True, verbose_name=' الى عنوان')),
                ('delivering_status', models.CharField(blank=True, choices=[('1', 'انتظار'), ('2', 'خروج'), ('3', 'تم')], default='1', max_length=10, null=True, verbose_name=' موقف التوصيل')),
                ('delivering_type', models.CharField(blank=True, choices=[('1', 'ذهاب'), ('2', 'عودة'), ('3', 'ذهاب و عودة')], default='1', max_length=10, null=True, verbose_name='  نوع العملية')),
                ('charge_price', models.FloatField(blank=True, null=True, verbose_name='  سعر التوصيل')),
                ('code', models.CharField(blank=True, editable=False, max_length=14, null=True, verbose_name='كود العملية')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='  ملاحظات ')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ تسجيل العملية')),
                ('from_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_client_relation', to='maindata.client', verbose_name=' من العميل')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.package', verbose_name=' الطلب')),
                ('to_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.client', verbose_name=' الى العميل')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.worker', verbose_name=' العامل الموكل')),
            ],
            options={
                'verbose_name': '   عملية شحن',
                'verbose_name_plural': '  عمليات الشحن ',
            },
        ),
    ]
