# Generated by Django 4.2.4 on 2024-02-02 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0013_alter_package_code_chargeoperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeoperation',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='chargeoperation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.chargeoperation', verbose_name=' الشحنة'),
        ),
    ]
