# Generated by Django 4.2.4 on 2024-02-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0014_remove_chargeoperation_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeoperation',
            name='delivering_type',
        ),
    ]
