# Generated by Django 4.2.4 on 2024-02-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0016_alter_chargeoperation_delivering_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='chargeoperation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.chargeoperation', verbose_name=' الشحنة'),
        ),
    ]
